### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by NicoNicoNi-Host** [insanum/obsidian_nord#47]
## Link color
The latest version of the theme has no distinction between the hyperlink color and the internal link color, and no distinction between the URL part and the text part of the hyperlink

Maybe it can restore old color scheme

```css
/* Internal Link Color */
.theme-light
{
    --text-accent:                   var(--frost3)!important ;
}

.theme-dark
{
    --text-accent:                   var(--frost3)!important ;
}

/* Hyperlinks and hover colors */
.cm-s-obsidian span.cm-link {
    color: var(--orange) !important ;
    word-break: break-word;
}

.cm-s-obsidian span.cm-link:hover
{
    color: #90EE90 !important;
    text-decoration: none !important;
}

```

![image](https://user-images.githubusercontent.com/35772908/195967237-ba8de673-f912-4794-bc0d-b9d9b3bd0467.jpeg)

**Comment by insanum** [comment]
Please break this up into separate issues for easier tracking.

**Comment by NicoNicoNi-Host** [comment]
color: #90EE90 ,This color is my random writing, I do not know art, so it is a little discordant, perhaps you can give me some advice

```css
.cm-s-obsidian span.cm-link:hover
{
    color: #90EE90 !important;
    text-decoration: none !important;
}
```
