### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by NicoNicoNi-Host** [insanum/obsidian_nord#48]
## Text color
In dark mode, when there is a lot of text, the text color will be blinding, perhaps the following colors can be adopted

```css
.theme-dark {
    --text-normal: #93a1a1;
    --text-faint: #93a1a1;
    --text-muted: #93a1a1;

 }

.markdown-preview-view blockquote {
    color: #93a1a1 !important ;
}
```

### before
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/35772908/195974179-b4a5ec2e-d0f4-4e89-ba05-f046730c0783.png">

### after
![image](https://user-images.githubusercontent.com/35772908/195974176-1e450a18-a281-415d-97f5-338185882d7b.jpeg)
