### ISSUE TITLE
search-match-highlight

### ISSUE THREAD

**Issue by NicoNicoNi-Host** [insanum/obsidian_nord#49]
## search-match-highlight
This will be more eye-catching

```css
.cm-s-obsidian span.obsidian-search-match-highlight {
    background-color: yellow;
}
```
